#
# node-docker-setup iota-v1.0.7
# https://github.com/iotaledger/node-docker-setup
#

services:

##################################################################
#  HORNET                                                        #
##################################################################

  hornet:
    labels:
      - "traefik.http.routers.hornet.entrypoints=websecure"
      - "traefik.http.routers.hornet.tls=true"
      - "traefik.http.routers.hornet.tls.certresolver=myresolver"

##################################################################
#  Reverse Proxy and SSL                                         #
##################################################################

  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--metrics.prometheus=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.websecure.proxyProtocol.trustedIPs=192.168.1.10"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # - "--log.level=DEBUG"
      # - "--accesslog=true"
    ports:
      - "443:443/tcp"
      - "8080:8080/tcp"


##################################################################
#  Monitoring                                                    #
##################################################################

  grafana:
    labels:
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"


##################################################################
#  INX Extensions                                                #
#  disable them out by commenting out the services               #
##################################################################

  inx-dashboard:
    labels:
      - "traefik.http.routers.hornet-dashboard.entrypoints=websecure"
      - "traefik.http.routers.hornet-dashboard.tls=true"

##################################################################
#  WASP                                                          #
##################################################################

  wasp:
    labels:
      - "traefik.http.routers.wasp-api.entrypoints=websecure"
      - "traefik.http.routers.wasp-api.tls=true"
      - "traefik.http.routers.sedimark-chain.entrypoints=websecure"
      - "traefik.http.routers.sedimark-chain.tls=true"

  wasp-dashboard:
    labels:
      - "traefik.http.routers.wasp-dashboard.entrypoints=websecure"
      - "traefik.http.routers.wasp-dashboard.tls=true"
      - "traefik.http.routers.wasp-dashboard2.entrypoints=websecure"
      - "traefik.http.routers.wasp-dashboard2.tls=true"
    environment:
      - WASP_API_URL=https://${NODE_HOST:-localhost}/wasp/api
      - L1_API_URL=https://${NODE_HOST:-localhost}
